stages:
- name: push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: testteretest:latest
      registry: index.docker.io
    when:
      event: {}
  when:
    event: {}
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./Deployment.yml
timeout: 60
branch:
  include:
  - master
