stages:
- name: push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: php-test:v1
    when:
      event:
        include:
        - push
timeout: 60
