stages:
- name: push image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: php-test
      registry: 127.0.0.1:34846
    when:
      event: {}
  when:
    event:
      include:
      - push
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./Deployment.yml
timeout: 60
branch:
  include:
  - master
