apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-example
  labels:
    app: php-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-example
  template:
    metadata:
      labels:
        app: php-example
    spec:
      imagePullSecrets:
      - name: redxice
      containers:
      - name: php
        image: ${CICD_IMAGE}:latest
        ports:
        - containerPort: 80